export const ADD_INVOICE = 'ADD_INVOICE';
export const INVOICE_LOADING ="INVOICE_LOADING";
export const INVOICE_FAILED ='INVOICE_FAILED';
export const DELETE_INVOICE ='DELETE_INVOICE';
export const DELETE_FAILED ='DELETE_FAILED';
export const EDIT_INVOICE= 'EDIT_INVOICE';
export const EDIT_FALIED= 'EDIT_FALIED';
export const FETCH_TABLE_DATA= 'FETCH_TABLE_DATA';



